# AutoRankUp
# made by 1stian
# https://ohneemc.com
#
settings:
  # Log rank ups to console? It will still print if something is wrong.
  console: true
  # How frequent do you want it to check for rank ups. In minutes.
  frequency: 5
  # Check if a player is eligible to rank up when they connect.
  login: true
  # Broadcast to all when a player ranks up?
  broadcast: true
  # You can color code these messages.
  # {player} - Being replaced with the player who's ranking up.
  # {rank_to} - Is the group the player ranked up to.
  broadcastmessage: "&b{player}&a, just ranked up to &6{rank_to}"
  # Whether or not to send a message to the player who ranks up.
  player: true
  # Message for the player who ranks up.
  playermessage: "&aGood job! &b{player}&a, you just ranked up to &6{rank_to}"
placeholder:
  # What placeholder to use, when grabbing a players rank. Example placeholder for LuckPerms: %luckperms_primary_group_name%
  group: ""
bungee:
  # If you want to send the broadcast message to your bungee network.
  broadcast: false
# Use vault for ranking up players.
vault:
  # If this is enabled, ensure you have vault installed! The command setting on each rank will be disabled.
  enabled: false
ranks:
  # The default rank of the server.
  default:
    # The time in days, hours and minutes . Don't change the format, only the numbers!
    time: 0d 3h 0m
    # The rank you want to put them in.
    to: regular
    # Command to send to the console on rank up. Example for LuckPerms: lp user {player} parent set {group}
    # Make sure you put {player} and {group} where they need to be in your command.
    command: ""
  regular:
    time: 1d 4h 0m
    to: trusted
    command: ""

# Please do not change or delete this!
ConfigVersion: 1.0