language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

before_install:
 - chmod +x gradlew

addons:
  sonarcloud:
    organization: "1stian"
    token:
      secure: "bPK49XysVsga3RX3k0nfmWwFtc9DmpeMhsCCw3i1bcHOFlYq++9Qf48IbPfXPOlL/WDdQ7KofY5R01Ijzg2aKi3pb1yTNTlXbgP+ctkHzw9MdMepUtF9vkpKx1hfDxdOV/KfiA8XJq4c+awFXvMkNb3ABT3udwbS1m5KABvntA8fa7pKZSXit+/poV+4P9My9pvhoU8KDrbgsCFyTxK3wMl7XZ3HPrWmsGqJ1QJsYmOsXqEns92Jy4Q6v4oi/QkSt2t0LCKSS2o5azWl7jXNL7FIU9BVAPbWkbNnkMOavYti9Ee/1i9D8Yh/2Ah5ENEcKD9FsUQDAjZ8qeBiJiLw7HIjj9oRYiB0uZUibQrDtFPzjrIUJANcQGxPZwoqRRiplijRxw8JeFmtEckkJeXQSUh+rW4HNCaqeYvHZyfCfLuKTNTJv7NsCFRrfP/KEPtv0/ixi4IYX7m/fKQEKoaxSIBg3+3U51mEaF+lNPofIBpNDI1y7rrBb69OBhs9QkQPthxB8uXZ1lK553obmAL5iYGilKQwUwjQb/ILaNRlQ4hP4bbN1V5PAqFQ0usg2k5R6eDsyLMuSz1Mx2z+AQM+7ny3obf90ZZK/YeveS7craVp1h/mv1YnGfg2egL7h4KXlddgd7PRwL1IUf1otis6p4MKYVjgqBnOwjYhMEDRzVc="
script:
  - ./gradlew build
  - ./gradlew sonarqube